export const images = {
  logo: require("@/assets/logo.svg"),
  infoRed: require("@/assets/info-circleRed.svg"),
  customerIcon: require("@/assets/user-square.svg"),
  rightCaret: require("@/assets/chevron-right.svg"),
  square: require("@/assets/3d-square.svg"),
  keydashboard: require("@/assets/key-square.svg"),
  income: require("@/assets/income.svg"),
  promote: require("@/assets/discount-shape.svg"),
  help: require("@/assets/help.svg"),
  avatar: require("@/assets/EllipseAvatar.svg"),
  downcaret: require("@/assets/chevron-down.svg"),
  searchIcon: require("@/assets/search.svg"),
  menu: require("@/assets/menu.svg"),
  arrowup: require("@/assets/arrow-up.svg"),
  arrowdown: require("@/assets/arrow-downn.svg"),
  totalCustomer: require("@/assets/totalCustomer.svg"),
  member: require("@/assets/member.svg"),
  activeNow: require("@/assets/active.svg"),
  Ellipse1: require("@/assets/Ellipse1.svg"),
  Ellipse2: require("@/assets/Ellipse2.svg"),
  Ellipse3: require("@/assets/Ellipse3.svg"),
  Ellipse4: require("@/assets/Ellipse4.svg"),
  Ellipse5: require("@/assets/Ellipse5.svg"),
  signOut : require("@/assets/SignOut.svg"),
};
